#!/bin/bash --login


__dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${__dir}"


echo "# # # # #"

# // TODO: Check for rvm. Install it? No, but convince me. Or open a PR :)
# // TODO: Check for python 3.7, preferably homebrew python. Install it? Pin it? Maybe, convince me. Or open a PR :)
# // TODO: If so, check for homebrew? Install it? No, but convince me. Or open a PR :)
# // TODO: Check for pip. Install it? Pin it? Maybe, convince me. Or open a PR :)
# // TODO: Check for virtualenv. Install it? Pin it? Maybe, convince me. Or open a PR :)

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Use/Install ruby as specified in .ruby-version and .ruby-gemset
rvm use "$(cat '.ruby-version')@$(cat '.ruby-gemset')" --create --install
#
# # # # # # # # # # # # # # # # #


echo "# # #"


# # # # # # # # #
# Install bundler
echo "Checking for bundler installation..."
GEM_SPEC_BUNDLER_OUTPUT=$( (gem spec bundler) 2>&1 )
GEM_NOT_FOUND=${GEM_SPEC_BUNDLER_OUTPUT::5}
if [[ $GEM_NOT_FOUND = "ERROR" ]];
then
    echo "bundler is not installed."
    echo "Installing bundler..."
    gem install bundler
else
    echo "bundler is already installed."
fi
#
# # # # # # # # #


echo "# # #"


# # # # # # # # # # #
# Run bundle install
echo "Running bundle install"
bundle install
#
# # # # # # # # # # #


echo "# # #"


# # # # # # # # # # #
# Create virtualenv 'licketysplit'
echo "Create virtualenv 'licketysplit'"
mkvirtualenv licketysplit
#
# # # # # # # # # # #


echo "# # #"


# # # # # # # # # # #
# Activate virtualenv 'licketysplit'
echo "Activate virtualenv 'licketysplit'"
. ./licketysplit/bin/activate
#
# # # # # # # # # # #


echo "# # #"


# # # # # # # # # # #
# Install dev-requirements.txt
echo "Run pip-sync dev-requirements.txt"
pip install -r dev-requirements.txt
#
# # # # # # # # # # #


echo "# # #"


# # # # # # # # # #
# Install git hooks
mkdir -p ".git/hooks/"
echo "Installing pre-push hook..."
cat <<\EOF > ".git/hooks/pre-push"
#!/bin/bash

./pre-push
EOF
chmod +x ".git/hooks/pre-push"
#
# # # # # # # # # #


echo "Done. Have fun developing!"
echo "# # # # #"
