#!/bin/bash --login


# # # # # # # # #
# Switch to directory containing this script
__dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo
echo "> Switching to ${__dir}"
cd "${__dir}"
# # # # # # # # #


# // TODO: Check for rvm. Install it? No, that should be up to the user, I think.
# // TODO: Check for python 3.7, preferably homebrew python. Install it? Pin it? Maybe.
# // TODO: If so, check for homebrew? Install it? No, that should be up to the user, I think.
# // TODO: Check for pip. Install it? Pin it? Maybe.
# // TODO: Check for virtualenv. Install it? Pin it? Maybe.
# For the 'maybe's, feel free to convince me why it should or shouldn't be done. Or open a PR :)

# # # # # # # # #
# Use/Install ruby as specified in .ruby-version and .ruby-gemset
__ruby_environment="$(cat '.ruby-version')@$(cat '.ruby-gemset')"
echo
echo "> Running rvm use ${__ruby_environment} --create --install"
rvm use "${__ruby_environment}" --create --install
#
# # # # # # # # #


# # # # # # # # #
# Check for/Install bundler
echo
echo "> Checking for bundler installation"
gem spec bundler >/dev/null 2>&1
if [[ $? -eq 0 ]];
then
	echo "> bundler is already installed."
else
    echo "> bundler is not installed."
    echo "> Installing bundler"
    gem install bundler
fi
#
# # # # # # # # #


# # # # # # # # #
# Run bundle install
echo
echo "> Running bundle install"
bundle install
#
# # # # # # # # #


# # # # # # # # #
# Create/Activate virtualenv 'licketysplit'
echo
echo "> Creating/activating virtualenv 'licketysplit'"
mkvirtualenv licketysplit
#
# # # # # # # # #


# # # # # # # # #
# Install pip-tools
echo
echo "> Installing pip-tools"
pip install pip-tools
#
# # # # # # # # #


# # # # # # # # #
# Install dev-requirements.txt
echo
echo "> Running pip-sync dev-requirements.txt"
pip-sync dev-requirements.txt
#
# # # # # # # # #


# # # # # # # # #
# Install pre-push hook
echo
echo "> Installing pre-push hook"
mkdir -p ".git/hooks/"
cat <<\EOF > ".git/hooks/pre-push"
#!/bin/bash

./pre-push
EOF
chmod +x ".git/hooks/pre-push"
#
# # # # # # # # #


echo
echo "> Done. Have fun developing!"
echo
